### PR TITLE
smooth dragging

### PR DESCRIPTION
**Pull request by xmuSistone**

### CODE REVIEW

**Comment by GIGAMOLE** [comment]
I did not see any improvments. Thanks fir attempt, but this is useless.

**Comment by xmuSistone** [comment]
Why not run in studio and try dragging

**Comment by GIGAMOLE** [comment]
I try it. Compile it, but this is nothing. There are no new drag smooth mechanics, just some click intercept.

**Comment by xmuSistone** [comment]
All right. Sorry for help nothing

**Pull request closed without merging**
